### ISSUE TITLE
Question about fine-tuning layer

### ISSUE THREAD

**Issue by bnestor** [zzachw/llemr#1]
Hi,

Can you describe where the linear layer is applied to the model for the fine-tuning experiments?
I am assuming it is somewhere like 
```
outputs = llmer(..., output_hidden_states=True)
logit = finetune_layer(outputs.hidden_states[:,0,:].reshape(batch_size, -1))
```
Are you specifically attending to the hidden state for the first token after the prompt?

Thanks.

**Comment by zzachw** [comment]
Thanks for the question!

We simply use the last token to do the classification as the backbone LLM
is decoder only.

Please let me know if you have any other questions.
