### ISSUE TITLE
Question about the use of MEDS

### ISSUE THREAD

**Issue by amrit110** [zzachw/llemr#2]
Hi!

In the paper, you mention the use of the Medical Event Standard (MEDS), but i don't see it used in the data pipeline. Could you please clarify that?

**Comment by zzachw** [comment]
Thanks for your question! We followed a similar high-level concept as the Medical Event Standard (MEDS), where each patient is represented by a list of events, with each event containing a timestamp and a list of measurements. However, we did not use the MEDS library to process or format the data.
